version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
      - python
    versioning-strategy: lockfile-only
  - package-ecosystem: "github-actions"
    directory: "/"
    labels:
      - dependencies
      - github_actions
    schedule:
      interval: "daily"
    commit-message:
      prefix: ⬆
